apiVersion: apps/v1
kind: Deployment
metadata:
  name: animated-drawings-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animated-drawings
  template:
    metadata:
      labels:
        app: animated-drawings
    spec:
      containers:
        - name: api-service
          image: registry.ferrari.snucse.org:30443/little-studio/server_run:2.0
          ports:
            - containerPort: 5000
        - name: torchserve
          image: registry.ferrari.snucse.org:30443/little-studio/torch_serve:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: animated-drawings-service
spec:
  type: ClusterIP
  selector:
    app: animated-drawings
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: torchserve
      protocol: TCP
      port: 8080
      targetPort: 8080

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: animated-drawings-ingress
# spec:
#   rules:
#     - host: [api-domain]
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: animated-drawings-service
#                 port:
#                   number: 80
#     - host: [torchserve-domain]
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: animated-drawings-service
#                 port:
#                   number: 8080