apiVersion: v1
kind: Service
metadata:
  name: animated-drawings-service
spec:
  type: ClusterIP
  selector:
    app: n201432420
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5000
    - name: torchserve
      protocol: TCP
      port: 8080
      targetPort: 8080
---
  apiVersion: v1
  kind: Service
  metadata:
    name: my-service
  spec:
    type: NodePort
    selector:
      app: n201432420
    ports:
      - name: http
        nodePort: 30001 # 노드의 30001번 포트로 들어오면
        port: 80 # 서비스의 80번 포트로 전달하고
        targetPort: 5000 # Pod의 80번 포트로 전달 30001(Node) -> 80(Service) -> 80(Pod)
        protocol: TCP
